### PR TITLE
Check system dependencies using pkg manager 

### LINKED ISSUE #106: Cannot open protected file created by Excel 2019
For XLConnect after 0.2-15 having trouble opening an Excel workbook with a password created by Excel 2019.

This is the same error as in [issue 103](https://github.com/miraisolutions/xlconnect/issues/103#issue-604853913).

> Error: NoClassDefFoundError (Java): com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory

In order to search the cause, I cloned the unit test file "testBug61.xlsx" , test it and worked it well.
```R
wb <- XLConnect::loadWorkbook("testBug61.xlsx", password = "mirai") # success
```

next, I tried my own excel file and failed.
```R
wb <- XLConnect::loadWorkbook("protectedWorkbook.xlsx", password = "pass")
> Error: NoClassDefFoundError (Java):  com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory
```

However, I saved the same workbook as xls (Excel 97-2003 version format) and successfully loaded.
```R
wb <- XLConnect::loadWorkbook("protectedWorkbook_old.xls", password = "pass") # success
```

To confirm that Excel version causes the load error, I decrypted  the "testBug61.xlsx" and encrypted again with Excel 2019.
Then, loadWorkbook failed again.
```R
wb <- XLConnect::loadWorkbook("testBug61_updated.xlsx", password = "mirai")
> Error: NoClassDefFoundError (Java):  com/microsoft/schemas/office/x2006/encryption/EncryptionDocument$Factory
```

From the results above, I suspect that Excel version might be the cause of loadWorkbook error.
I could not search further since I have Excel only version 2019, but I will report if I find something more informative.

Thank you.

### PR DESCRIPTION
**Pull request by spoltier**
... and fix copy-paste error in definition of system dependencies.
Closes #106 and #103 
Needed for next CRAN submission.

- [x] investigate macOS options (homebrew ?)

### CODE REVIEW

**Comment by spoltier** [comment]
Added the WIP commits of #116 to get checks running on this.

**Comment by spoltier** [comment]
No common macOS package manager offering commonly used JARs.
Working on suppressing warnings from `system2` when packages are not found - `suppressWarnings` is not enough for the CI environment.

**Comment by spoltier** [comment]
see miraisolutions/xlconnect-java#7

File: R/checkSystemPackage.R [hunk 1]
```diff
@@ -0,0 +1,65 @@
+#############################################################################
+#
+# XLConnect
+# Copyright (C) 2010-2020 Mirai Solutions GmbH
```
Comment (martinstuder) [inline R/checkSystemPackage.R:4]: We should probably update the Copyright headers in all the files

File: R/checkSystemPackage.R [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+#############################################################################
+
+#############################################################################
+#
+# XLConnect Package Installation: find system packages by name, including
+# installed files, using Debian or Red Hat package managers
+# 
+# example: with
```
Comment (martinstuder) [inline R/checkSystemPackage.R:26]: Remove "example: with"

File: R/checkSystemPackage.R [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+#############################################################################
+
+ checkSystemPackage <- function (debianpkgname, rpmpkgname, versionpattern) {
+  dpkg <- function(args) {
+    suppressWarnings(system2("dpkg", args, stdout = TRUE, stderr = TRUE))
+  }
+  rpm <- function(args) {
+    suppressWarnings(system2("rpm", args, stdout = TRUE, stderr = TRUE))
+  }
+  distro <- function(distroName) {
```
Comment (martinstuder) [inline R/checkSystemPackage.R:39]: Could we add other Linux distros to the CI build matrix? E.g. RHEL, Fedora and Debian?

File: R/onLoad.R [hunk 4]
```diff
@@ -27,53 +27,60 @@
...
+    # Java version check, without .jinit (we do .jpackage after downloading resources)
+    rawVersion <- system2("java", c("-version"), stdout = TRUE, stderr = TRUE)
+    jv <- regmatches(rawVersion[1], regexpr("[0-9]+\\.[0-9\\.]*", rawVersion[1]))
+    twoFirst <- substr(jv, 1L, 2L)
+    if(twoFirst == "1.") {
+      jvn <- as.numeric(substr(jv,3L,3L))
+    } else {
+      jvn <- as.numeric(twoFirst)
+    }
+    if (jvn<8 || jvn>15) stop(paste0("Installed java version ",jv ," is not between Java>=8 and <=15! This is needed for this package"))
```
Comment (martinstuder) [inline R/onLoad.R:41]: I would probably change this message slightly to something like "XLConnect requires Java >= 8 and <= 15. Detected version of Java is X".

File: cran-comments.md [hunk 5]
```diff
@@ -1,25 +1,19 @@
...
-
 # Test Environments
 
-* Ubuntu 18.04 on Travis CI
-* Ubuntu 16.04 on Travis CI
-* CRAN winbuilder
-* Ubuntu Linux 16.04 LTS, R-release, GCC on r-hub
+* Ubuntu 18.04 on Github Actions
+* Ubuntu 16.04 on Github Actions
+* Windows 10 (2019) on Github Actions
```
Comment (martinstuder) [inline cran-comments.md:5]: See above. Could we extend with a few additional Linux distros? Mainly to test installation of dependencies.

File: cran-comments.md [hunk 6]
```diff
@@ -1,25 +1,19 @@
...
 There was 1 NOTE:
 > checking installed package size ... NOTE
-  installed size is 28.8Mb
-  sub-directories of 1Mb or more:
-    java  26.2Mb
+    installed size is 36.3Mb
+    sub-directories of 1Mb or more:
+      java  34.0Mb
 
 Justification: XLConnect uses a java component which we maintain in a separate project, as well as Apache POI 4.1.1 and
```
Comment (martinstuder) [inline cran-comments.md:18]: Apache 4.1.2

Should we mention here that dependencies are download on install? Should be clear though since the submitted tarball will be small.

File: inst/unitTests/runit.workbook.clearSheet.R [hunk 7]
```diff
@@ -1,47 +1,47 @@
...
-	# Check that clearing sheets returns empty sheets (*.xlsx)
-	clearSheet(wb.xlsx, c("clearSheet1", "clearSheet2"))
-	res1 <- getLastRow(wb.xlsx, "clearSheet1")
-	res2 <- getLastRow(wb.xlsx, "clearSheet2")
-	checkEquals(c(res1, res2), c(clearSheet1 = 1, clearSheet2=1))
-
+#############################################################################
+#
+# XLConnect
+# Copyright (C) 2010-2018 Mirai Solutions GmbH
```
Comment (martinstuder) [inline inst/unitTests/runit.workbook.clearSheet.R:4]: Outdated Copyright header

**Review by martinstuder — COMMENTED** [review]
- `inst/COPYRIGHTS` probably requires updating the copyright year range for Apache POI
- `README.md` install note should mention latest version (or use a generic placeholder instead)

File: R/checkSystemPackage.R (hunk 3 above)
Comment (spoltier) [reply R/checkSystemPackage.R:39]: Can try, but it doesn't come as part of GH actions hosted environments. It's possible to use docker containers, but some open source actions we use (e.g. setting up Java, setting up R.) might not support other distros.

Comment (spoltier) [reply R/checkSystemPackage.R:37]: As expected, using containers we can't use the recommended actions for setting up java, R, and existing docker images are missing some of the dependencies we need (rocker - debian based - doesn't have java, there's an unmaintained centos7 + R image which probably we shouldn't use anyway).
See e.g. https://github.com/miraisolutions/xlconnect/actions/runs/536526701 and other actions failing on the same day.

My attempts at making GH actions work with containers are on branch https://github.com/miraisolutions/xlconnect/tree/custom/gh-actions-container.

I can start working on a complete centos / red hat UBI / debian docker image for testing XLConnect, but I'm not sure if that should be part of this PR.
I have of course tested the package resolution manually on centos.

Comment (spoltier) [reply R/checkSystemPackage.R:37]: Following up with #121

File: cran-comments.md (hunk 5 above)
Comment (spoltier) [reply cran-comments.md:5]: Following up with #121
