### PR TITLE
#212 Test loadWorkbook works with relative paths

### LINKED ISSUE #212: Bug: loadWorkbook fails to open files in XLConnect v1.0.8 if full path is not specified
### sessionInfo() output

R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Portugal.utf8  LC_CTYPE=Portuguese_Portugal.utf8   
[3] LC_MONETARY=Portuguese_Portugal.utf8 LC_NUMERIC=C                        
[5] LC_TIME=Portuguese_Portugal.utf8    

time zone: Europe/Lisbon
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] XLConnect_1.0.8

loaded via a namespace (and not attached):
[1] compiler_4.3.2    tools_4.3.2       rstudioapi_0.15.0 readODS_2.2.0     rJava_1.0-11 

### Additional environment information

_No response_

### Description

Loading any Excel file (XLS or XLSX) fails because the file is not found

### Expected behavior

File opens with loadWorkbook("Word_Another.xls")

### How to Reproduce

1) Set your work folder e.g. setwd("C:/Users/plino/")
2) Open file with loadWorkbook("Word_Another.xls")
3) Error: NoSuchFileException (Java): Word_Another.xls
4) Open file with loadWorkbook("C:/Users/plino/Word_Another.xls")
5) Success

This is a regression from 1.0.7 where the two step method worked.
It is probably a simple code fix but I'm not a programmer :)

### PR DESCRIPTION
**Pull request by martinstuder**
Edit @spoltier:
Closes #212 with code from miraisolutions/xlconnect-java#34

### CODE REVIEW

File: inst/unitTests/runit.loadWorkbook.R [hunk 1]
```diff
@@ -87,4 +87,9 @@ test.loadWorkbook <- function() {
 	# correct password is specified
 	# Excel2019
 	wb <- loadWorkbook(pwdProtectedFile, password = "mirai")
+
+	# Check that loadWorkbook can handle relative paths (#212)
+	setwd(rsrc("resources"))
```
Comment (spoltier) [inline inst/unitTests/runit.loadWorkbook.R:92]: key to the bug is that the working directory is set in R during runtime, and the JVM doesn't completely "follow" that.

**Review by spoltier — APPROVED** [review]
